@startuml
hide footbox
title Use Case 1: Create Table

actor User

participant MainWindow
participant SubwindowManager
participant MouseInteractionDispatcher
participant EditAnySubwindow
participant TableSubwindow
participant TablesController
participant TableRepository
participant NameGenerator
participant Table

User -> MainWindow : double-click
activate MainWindow
MainWindow -> SubwindowManager : handleMouseEvent(...)
activate SubwindowManager
SubwindowManager -> SubwindowManager : findSubwindowAt(...)
SubwindowManager --> SubwindowManager : target
SubwindowManager -> SubwindowManager : bringToFront(target)
SubwindowManager -> MouseInteractionDispatcher : dispatchMouseEvent(...)
activate MouseInteractionDispatcher
MouseInteractionDispatcher -> EditAnySubwindow : wantsToHandle(...)
activate EditAnySubwindow
EditAnySubwindow --> MouseInteractionDispatcher : true
deactivate EditAnySubwindow
MouseInteractionDispatcher -> EditAnySubwindow : handle(...)
activate EditAnySubwindow
EditAnySubwindow -> TableSubwindow : handleMouseEvent(...)
activate TableSubwindow
TableSubwindow -> TableSubwindow : isInAddTableArea(...)
TableSubwindow -> TablesController : handleCreateNewTableRequest()
activate TablesController
TablesController -> TableRepository : createNewTable()
activate TableRepository
TableRepository -> NameGenerator : generateUniqueName(...)
activate NameGenerator
NameGenerator --> TableRepository : name
deactivate NameGenerator
TableRepository -> Table : Table(name)
activate Table
Table --> TableRepository : table
deactivate Table
TableRepository --> TablesController : void
deactivate TableRepository
TablesController --> TableSubwindow : void
deactivate TablesController
TableSubwindow --> EditAnySubwindow : void
deactivate TableSubwindow
EditAnySubwindow --> MouseInteractionDispatcher : void
deactivate EditAnySubwindow
MouseInteractionDispatcher --> SubwindowManager : void
deactivate MouseInteractionDispatcher
SubwindowManager --> MainWindow : void
deactivate SubwindowManager
MainWindow --> User
deactivate MainWindow
@enduml